### ISSUE TITLE
Custom titles for widgets

### ISSUE THREAD

**Issue by jonnyscholes** [plouc/mozaik#113]
Hi there - we're looking at using this at Takeflight where we have dozens of client projects each with their own repo, analytics, servers etc. I'm hoping to be able to have a few dashboards that give us some insight into our overall progress and stats on all projects. 

Currently for most extensions if I add more than one widget for different projects they end up with the same title (eg GitLab merge request guage). I'm keen to enable Widgets to have their own custom title. It looks like that would be the responsibility of each individual extension. Before I go and submit PRs to various projects I just want to make sure thats correct and that in V2 that won't change (or that I'm not missing something).

Thanks for the awesome project!

**Comment by plouc** [comment]
@jonnyscholes, thank you for your interest for Mozaïk.

You're right, it's the responsibility of each extensions, because some could have no title at all and others such as `mozaik-ext-time` use placeholders for titles.

`mozaik-ext-github` offers title override, but most of the others don't.

If you don't mind (and use it of course), I'll be happy to add Takeflight to the Mozaïk references :)

**Comment by plouc** [comment]
You can also use dashboard title if you have one for each project.

**Comment by plouc** [comment]
A final note, Mozaïk v2 will change the way you install/configure it, but if you don't develop custom extensions/themes, you could just install the v2 and update the config file.
