### ISSUE TITLE
Can't seem to run mozaik v2 in development mode

### ISSUE THREAD

**Issue by knackjax** [plouc/mozaik#130]
Modified package.json to have development server to run on the same port.
....
  "scripts": {
    "start": "PORT=5000 react-scripts start",
     ....
  }
...

However I get connection refused issues (Error 500) when the dashboard loads
An error occurred while fetching configuration: Unable to fetch configuration: Internal Server Error (500) 

In terminal

Compiled successfully!

You can now view mozaik-demo in the browser.

  Local:            http://localhost:5000/
  On Your Network:  http://x.x.x.x:5000/

Note that the development build is not optimized.
To create a production build, use yarn build.

Proxy error: Could not proxy request /config from localhost:5000 to http://localhost:5000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

**Comment by juhamust** [comment]
@plouc is there a public repo for [mozaik.rocks](http://mozaik.rocks/) site? So that people could suggest additions or fixes via PRs?

**Comment by plouc** [comment]
https://github.com/plouc/mozaik-website

**Comment by pagameba** [comment]
I also cannot get this to work.  I tried running `node server.js` in a separate process followed by `yarn start`.  The resulting error is

    An error occurred while fetching configuration: Unexpected token < in JSON at position 0

which happens loading the `/config` endpoint from localhost:3000 and the response contains the HTML content of the page rather than the configuration.  The dev server (unsurprisingly) fails to start with `PORT=5000 yarn start` because there is something else running on 5000.

Running `yarn build` then `node server.js` works fine.

I'm just starting to learn about the react ecosystem so I don't even know where to start debugging this.

**Comment by plouc** [comment]
@pagameba, config should be served on 3000 because of the proxy https://github.com/plouc/mozaik/blob/v2.x/examples/basic/package.json#L20

**Comment by pagameba** [comment]
Brilliant!  For some reason I removed the proxy config while trying to get stuff to work, thanks working great now!
