### ISSUE TITLE
Does Mozaik require reflux?

### ISSUE THREAD

**Issue by andrerpena** [plouc/mozaik#48]
First.. Thanks for this project. It looks amazing.
I'm wonder whether it works with other flux implementations like Redux.
My question is because including Reflux on my bundle would make it even bigger.
Thanks

**Comment by plouc** [comment]
@andrerpena, Unfortunately Mozaïk actually requires Redux

**Comment by plouc** [comment]
@andrerpena, I mean reflux, sorry

**Comment by andrerpena** [comment]
Thanks @plouc. I'm working on an open platform for creating data-driven business apps using the stack: Node + RethinkDB + React. Dashboards are essential for this kind of app.

I don't mean to undervalue your work. Mozaik is amazing. However, shouldn't the UI components be separated from the client-to-server communication? I would even have put the communication in a separate library. I wanted to be able to leverage all the UI from Mozaik and take care of the communication myself. In fact, the communication should be **optional**. If you want to feed all the UI components with json, feel free to do it. You want Mozaik to take care of the communication, great, here a lib.

Thank you @plouc. Again, Mozaik seems great!

**Comment by plouc** [comment]
@andrerpena, thanks for your feedback. I agree it should be great if **Mozaïk** supports this type of decoupling, unfortunately, the initial intent was to build a sort of *dashboard framework*, and I had a lot of difficulties to allow extension integration while keeping the ease of integration, perhaps **npm3** will make it painless. BTW, I think it could be easy to develop your own **Mozaïk** extensions using your current backend stack, because instead of fetching data through API calls, you could use RethinkDB `.changes()` feature.  Let me know if I can help, your project seems great.
