### ISSUE TITLE
Reload config and reconnect clients on server restart

### ISSUE THREAD

**Issue by plouc** [plouc/mozaik#73]

**Comment by tomav** [comment]
I'm running my dashboard in a docker container.
When a change is done to configuration, a new image is built and deployed.
This mean that the server restarts but doesn't know that some clients were connected, so there's no data polling, and no updates on connected clients.

When using a dashboard on a TV (without easy access to keyboard/mouse), it's a big problem.
Each client has to refresh the page to get futures updates (new widget added if conf changed, and also existing widget updates is a build status changed).

The purpose of this issue is to fix this behaviour?

**Comment by plouc** [comment]
@tomav, yes it is, but there's another problem with disconnected clients.

This one isn't easy to solve because I made the (questionable) choice of having a javascript based config file, so it's loaded as a simple module (using `require`) which cache it, I've fixed it for styles generation when you change the `theme` (see https://github.com/plouc/mozaik/blob/master/gulp/tasks/styles.js#L17), but I'm not very found of this *hack*. Switching to json could ease it, but it won't be BC.

I've thought of another approach, abstracting the config so you could have for example a json based config, or having it stored in RethinkDB or whatever, but I think it'll require a lot of work.

I'll think more seriously about it, I agree it's a big issue when you use it on TV (which is one of the purpose of this tool :/).

**Comment by plouc** [comment]
@tomav, there's a WIP which should fix your problem, now you'll have a notification when the ws connection is broken, then the frontend will attempt to reconnect it 10 times each 15 seconds, see https://github.com/plouc/mozaik/pull/77.

**Comment by tomav** [comment]
Great!

**Comment by plouc** [comment]
@tomav available in `mozaik@1.4.0`

**Comment by tomav** [comment]
Upgrading! Thank.

**Comment by plouc** [comment]
@tomav 1.4.1, there's a bug in 1.4.0

**Comment by tomav** [comment]
Ok.

**Comment by tomav** [comment]
Works great! 👍
